2021/02/19 14:34:41 : orders_errors 1: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4223, in after_order_import
    '_customer_user': convert['client_customers_id'] if convert['client_customers_id'] else 0,
KeyError: 'client_customers_id'

2021/02/19 14:34:41 : orders_errors 2: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4223, in after_order_import
    '_customer_user': convert['client_customers_id'] if convert['client_customers_id'] else 0,
KeyError: 'client_customers_id'

2021/02/19 14:34:41 : orders_errors 3: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4223, in after_order_import
    '_customer_user': convert['client_customers_id'] if convert['client_customers_id'] else 0,
KeyError: 'client_customers_id'

2021/02/19 14:34:41 : orders_errors 4: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4223, in after_order_import
    '_customer_user': convert['client_customers_id'] if convert['client_customers_id'] else 0,
KeyError: 'client_customers_id'

2021/02/19 14:34:41 : orders_errors 5: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4223, in after_order_import
    '_customer_user': convert['client_customers_id'] if convert['client_customers_id'] else 0,
KeyError: 'client_customers_id'

2021/02/19 14:34:41 : orders_errors 6: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4223, in after_order_import
    '_customer_user': convert['client_customers_id'] if convert['client_customers_id'] else 0,
KeyError: 'client_customers_id'

2021/02/19 14:34:41 : orders_errors 7: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4223, in after_order_import
    '_customer_user': convert['client_customers_id'] if convert['client_customers_id'] else 0,
KeyError: 'client_customers_id'

2021/02/19 14:34:41 : orders_errors 8: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4223, in after_order_import
    '_customer_user': convert['client_customers_id'] if convert['client_customers_id'] else 0,
KeyError: 'client_customers_id'

