2021/02/18 08:11:52 : Category id 2 import failed.
2021/02/18 08:11:52 : Category id 3 import failed.
2021/02/18 08:11:52 : Category id 4 import failed.
2021/02/18 08:11:52 : Category id 5 import failed.
2021/02/18 08:11:54 : Category id 6 import failed.
2021/02/18 08:11:54 : Category id 7 import failed.
2021/02/18 08:11:54 : Category id 8 import failed.
2021/02/18 08:11:54 : Category id 9 import failed.
2021/02/18 08:11:56 : Category id 10 import failed.
2021/02/18 08:11:56 : Category id 11 import failed.
2021/02/18 08:11:56 : Category id 12 import failed.
2021/02/18 08:11:56 : Category id 13 import failed.
2021/02/18 08:11:57 : Category id 14 import failed.
2021/02/18 08:11:58 : Category id 15 import failed.
2021/02/18 08:11:58 : Category id 16 import failed.
2021/02/18 08:11:58 : Category id 17 import failed.
2021/02/18 08:11:59 : Category id 19 import failed.
2021/02/18 08:11:59 : Category id 20 import failed.
2021/02/18 08:11:59 : Category id 22 import failed.
2021/02/18 08:11:59 : Category id 23 import failed.
2021/02/18 08:12:04 : products_errors 9: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:04 : products_errors 10: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:04 : products_errors 16: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:04 : products_errors 17: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:06 : products_errors 18: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:06 : products_errors 19: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:06 : products_errors 20: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:06 : products_errors 22: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:08 : products_errors 23: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:08 : products_errors 24: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:08 : products_errors 25: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:08 : products_errors 37: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : products_errors 39: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : products_errors 41: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : products_errors 42: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : products_errors 43: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : products_errors 44: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : products_errors 47: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : products_errors 48: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : products_errors 49: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3428, in product_import
    return response_success(product_import)
NameError: name 'product_import' is not defined

2021/02/18 08:12:09 : customers_errors 1: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3628, in customer_import
    self.insert_map(self.TYPE_CUSTOMER, convert['id'], customer_id, convert['code'])
NameError: name 'customer_id' is not defined

2021/02/18 08:12:09 : customers_errors 3: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 3628, in customer_import
    self.insert_map(self.TYPE_CUSTOMER, convert['id'], customer_id, convert['code'])
NameError: name 'customer_id' is not defined

2021/02/18 08:12:10 : orders_errors 1: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4043, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/18 08:12:10 : orders_errors 2: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4043, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/18 08:12:10 : orders_errors 3: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4043, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/18 08:12:10 : orders_errors 4: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4043, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/18 08:12:10 : orders_errors 5: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4043, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/18 08:12:10 : orders_errors 6: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4043, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/18 08:12:10 : orders_errors 7: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4043, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

2021/02/18 08:12:10 : orders_errors 8: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/woocommerce.py", line 4043, in order_import
    self.insert_map(self.TYPE_ORDER, convert['id'], order_id, convert['code'])
NameError: name 'order_id' is not defined

