2021/02/15 04:11:08 : Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1000, in migration
    ext = fn_get_ext(mains)
  File "/var/www/python/cartmigration/models/cart/custom.py", line 493, in get_products_ext_export
    image_ids=duplicate_field_value_from_list(product_ext['data']['products_images'], 'image_id')
KeyError: 'products_images'

2021/02/15 04:11:08 : Traceback (most recent call last):
  File "/var/www/python/bootstrap.py", line 20, in <module>
    getattr(controller, action_name)(data)
  File "/var/www/python/cartmigration/controllers/migration.py", line 86, in start
    self.run()
  File "/var/www/python/cartmigration/controllers/migration.py", line 139, in run
    self.send_email_to_dev(False, result.get('msg'))
  File "/var/www/python/cartmigration/libs/base_controller.py", line 779, in send_email_to_dev
    migration = getattr(migration_model, 'get_info_migration')(self._migration_id)
  File "/var/www/python/cartmigration/models/migration.py", line 73, in get_info_migration
    return getattr(self.get_abstract_migration(), 'get_info_migration')(migration_id)
AttributeError: 'NoneType' object has no attribute 'get_info_migration'

