2021/02/16 10:48:45 : orders_errors 1: Traceback (most recent call last):
  File "/var/www/python/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/var/www/python/cartmigration/models/cart/shopify.py", line 2974, in order_import
    if convert['shipping_address']['state']['name'] or convert['shipping_address']['state']['code']:
KeyError: 'state'

